[versions]
kotlin = "2.0.21"
agp = "8.13.2"
espresso = "3.5.1"
uiautomator = "2.3.0"
allure = "2.4.0"
junit = "4.13.2"
androidxTestCore = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTestRules = "1.5.0"
composeUiTest = "1.6.1"
clikt = "4.2.2"

[libraries]
# AndroidX Test
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }

# Espresso
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }

# UIAutomator
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }

# Compose UI Test
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUiTest" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiTest" }

# Allure
allure-kotlin-android = { module = "io.qameta.allure:allure-kotlin-android", version.ref = "allure" }
allure-kotlin-model = { module = "io.qameta.allure:allure-kotlin-model", version.ref = "allure" }
allure-kotlin-commons = { module = "io.qameta.allure:allure-kotlin-commons", version.ref = "allure" }

# JUnit
junit = { module = "junit:junit", version.ref = "junit" }

# CLI (for extract-screenshots)
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
